alexandria/core/filters.py, alexandria/core/tests/test_filters.py, alexandria/core/views.py
This commit implements a `JSONValueFilter` and adds a FilterSet to the
documents view.
The value for this filter needs to be json encoded als has the following
structure:
```python
[
{
"key": "some-key",
"value": "some value",
"lookup": "contains",  # optional, defaults to "exact"
},
...
]
```
Multiple lookups are ANDed.
=> feat(filter): add meta filter

alexandria/core/filters.py, alexandria/core/tests/test_filters.py, alexandria/core/views.py
This commit adds a filter `category` to the `tag` view. This filter
makes sure, only tags are returned, that actually have at least one
document in the provided category.
Closes #54
=> feat(tags): add category filter

alexandria/core/serializers.py, alexandria/core/tests/snapshots/snap_test_api.py, alexandria/core/tests/test_slugmodels.py
When creating slug model objects, the slug (primary key) was not generated
(and also not accepted via API, as it was the primary key), thus we would create
an object with an empty-string primary key, which obviously is not going to work
cd @fkm-adfinis
=> fix(slug models): make creation of slug models work correctly

alexandria/core/serializers.py, alexandria/core/tests/snapshots/snap_test_api.py, alexandria/core/tests/test_slugmodels.py
The attributes `created-by-group` and `created-by-user` were incorrectly
set for updates only, instead of new instances
=> fix(validation): correctly set created-by-(user/group)

alexandria/core/filters.py, alexandria/core/serializers.py, alexandria/core/tests/test_filters.py, alexandria/core/tests/test_views.py, alexandria/core/views.py
Add a new `activeGroup` filter to tell the backend who the user is currently acting as.
Also allow the frontend to pass in `modifiedByGroup` and `createdByGroup` parameters, and validate those against the user's actual groups
=> Feat: Active Group

alexandria/core/filters.py, alexandria/core/tests/test_filters.py
The tag filter on the documents endpoint should accept multiple tags.
This allows the filter to do `?filter[tags]=foo,bar`, which will only
list documents which have both "foo" and "bar" tags.
cc @fkm-adfinis
=> fix(filters): tag filter should accept multiple values

alexandria/core/factories.py, alexandria/core/serializers.py, alexandria/core/tests/snapshots/snap_test_api.py, alexandria/core/tests/test_slugmodels.py, alexandria/core/tests/test_views.py
In some cases (updates!), created_by_group was validated against
the current user instead of the existing object's user. So
the whole validation in BaseSerializer was refactored to work
a lot cleaner.
=> fix: correctly handle created_by_group, updated_by_group

alexandria/core/tests/snapshots/snap_test_api.py, alexandria/core/tests/test_filters.py, alexandria/core/views.py
The with_documents_in_category filter can duplicate tags, so we
deduplicate the results upfront.
This is easier here than to apply selectively when the filter is active,
and shouldn't impact performance.
=> fix: deduplicate tags

alexandria/core/filters.py
This allows limiting display of tags to only those that are
attached to documents with a specific meta value.
For example, when used with Caluma, you could put a caluma
case ID in the document's meta field, and then get only the
tags that are used within the context of a given case.
=> feat: with_documents_meta filter for tags

alexandria/core/filters.py, alexandria/core/tests/test_filters.py
The JSONValueFilter gets the possible `meta` lookups from the referenced field, but in a way that didn't work when the referenced field was accessed indirectly (ie. not a field on the current model).
=> Fix tag filter

README.md, alexandria/oidc_auth/authentication.py, alexandria/oidc_auth/tests/test_authentication.py, alexandria/settings.py
Introduce a fake auth backend that can be used mainly for frontend
development, without the need of setting up a full auth infrastructure.
You can set the following env variables to enable it:
```
DEV_AUTH_BACKEND=true
DEBUG=true
```
Note that `DEBUG=true` is explicitly required, so the fake auth backend
doesn't accidentally leak into production.
=> feat(dev): fake auth backend

README.md, alexandria/conftest.py, alexandria/core/apps.py, alexandria/core/serializers.py, alexandria/core/tests/test_validation.py, alexandria/core/validation.py, alexandria/settings.py, docs/validation.md
Introduce custom validation layer, similar to the already-existing
permission and visibility classes.
This allows implementors to define additional validations and extend Alexandria.
Usesful for example when incoming data needs to be checked for additional criteria.
=> feat: custom validations

alexandria/conftest.py
Username claim shouldn't be hardcoded - if it's different than "sub" in
an implemented project, the fixtures won't work
=> fix(ci): use correct claims for username

uwsgi.ini
UWSGI has a buffer of 4096 bytes by default, in which all request headers
must fit. If a user has particularly many roles/groups in their JWT token,
this limit is exceeded. UWSGI will then abort the request, and the reverse
proxy in front will respond with an error such as HTTP/502.
=> fix: extend uwsgi buffer

alexandria/core/filters.py, docker-compose.override.yml
Since files don't have the `case-id` on their meta, depending on the way that alexandria is being served, we might have to pass `filter[document-meta]` to the zip route which is implemented in this PR.
I also added two missing minio config vars in the `docker-compose.override.yml` which mean that this can actually be tested when running the `ember-alexandria` frontend (given that `minio` is routed to localhost).
=> fix: add the document_meta filter

CHANGELOG.md, alexandria/alexandria_metadata.py
* Add the document_meta filter ([`6921558`](https://github.com/projectcaluma/alexandria/commit/692155820033dfd8737ad2f53305658b2de5475f))
* Extend uwsgi buffer ([`e2863e9`](https://github.com/projectcaluma/alexandria/commit/e2863e9b3eff2f7d485531a1ea32d24f262812c5))
=> chore: new release

CHANGELOG.md, pyproject.toml
* Add pypi deployment worklow ([`8c341cc`](https://github.com/projectcaluma/alexandria/commit/8c341ccf0a293d6def06abae82347a1a9a6aef98))
* Split settings for packaging ([`7827984`](https://github.com/projectcaluma/alexandria/commit/7827984391cccac3440e8e54c01a414692910f9b))
* Use caluma-alexandria as package name ([`9baec0d`](https://github.com/projectcaluma/alexandria/commit/9baec0dfc88abf65c19dd4f659d06e7a48f1ec12))
* Relax version ranges ([`25fbb68`](https://github.com/projectcaluma/alexandria/commit/25fbb6833f6bebdf24fe526ea745a7d010a5ac3b))
* Fix jsonfilter ([`551d1e2`](https://github.com/projectcaluma/alexandria/commit/551d1e2fdd3d5245df0ae3b98a4a787b0b708853))
* Rename fields to metainfo and variant ([`4bfb7ed`](https://github.com/projectcaluma/alexandria/commit/4bfb7ed4aa149df0cdde …
=> chore: release v1.0.0

alexandria/core/apps.py, alexandria/settings/alexandria.py
deprecate PERMISSION_CLASSES, VISIBILITY_CLASSES, VALIDATION_CLASSES new config keys are
ALEXANDRIA_PERMISSION_CLASSES
ALEXANDRIA_VISIBILITY_CLASSES
ALEXANDRIA_VALIDATION_CLASSES
used https://github.com/projectcaluma/emeis/blob/main/emeis/settings.py as a reference
=> feat: prefix config keys

CHANGELOG.md, pyproject.toml
* Make properties for created_by configurable ([`c18dc06`](https://github.com/projectcaluma/alexandria/commit/c18dc06224fd8bf25090fc64906ac058aac8024f))
* Let the oidc user model be configurable ([`74c673a`](https://github.com/projectcaluma/alexandria/commit/74c673aff740b2c495f36ed4ca67468f8fd140e3))
* Extract serializer permissions ([`775f2b7`](https://github.com/projectcaluma/alexandria/commit/775f2b7f56fd822e644fea04bf96a6857e8c9609))
* Use correct minio error ([`86ef544`](https://github.com/projectcaluma/alexandria/commit/86ef5442f2cfb3d9a094a26f071a38e258ff6a4e))
=> chore: release v1.2.0

CHANGELOG.md, pyproject.toml
* Return documents from child categories ([`b992a3f`](https://github.com/projectcaluma/alexandria/commit/b992a3f1cbc045e6a4bb8eb64c822b0cb3a462e9))
* **document:** Add categories filter ([#351](https://github.com/projectcaluma/alexandria/issues/351)) ([`a9cb293`](https://github.com/projectcaluma/alexandria/commit/a9cb293ae5211eae8688e8b15305be011bbd4a74))
* **zip:** Append number to duplicate file names ([#337](https://github.com/projectcaluma/alexandria/issues/337)) ([`8f09c5f`](https://github.com/projectcaluma/alexandria/commit/8f09c5f0c304764a8a71afa451cbe2e9fa76d5fe))
=> chore: bump to v2.3.0

alexandria/core/filters.py
Context: We'd like to avoid having multiple tags with the same names that only differ in their case.
=> fix(filter): change to iexact for name search

CHANGELOG.md, pyproject.toml
* Remove dry from encryption command ([`a3a7238`](https://github.com/projectcaluma/alexandria/commit/a3a72389450c547acaf6888055242fb8abf23fda))
* Minor cleanups, disable encryption in local setup ([`033da5e`](https://github.com/projectcaluma/alexandria/commit/033da5e2edf2033124b597850784abb085caf947))
* **model:** Max length of file field ([`7d4b0c9`](https://github.com/projectcaluma/alexandria/commit/7d4b0c9061276a03ba3d08019ab212eb95334fe3))
=> chore(release): v3.0.0-beta.6

README.md, alexandria/conftest.py, alexandria/core/management/commands/encrypt_files.py, alexandria/core/tests/test_commands.py, alexandria/core/tests/test_views.py, alexandria/settings/alexandria.py, alexandria/storages/backends/s3.py, alexandria/storages/fields.py, alexandria/storages/tests/test_dynamic_field.py
BREAKING CHANGE: Instead of overwriting `DEFAULT_FILE_STORAGE` in the host app, Alexandria now uses a separate setting `ALEXANDRIA_FILE_STORAGE` to configure the used file storage backend.
=> feat(storage): don't use django default storage configuration

README.md, alexandria/conftest.py, alexandria/core/serializers.py, alexandria/settings/alexandria.py, alexandria/settings/django.py, poetry.lock, pyproject.toml
This adds django_clamd for AV scanning capabilites with ClamAV.
The scanning can be enabled through the settings.
=> feat(security): add ClamAV integration

CHANGELOG.md, pyproject.toml
* **security:** Add ClamAV integration ([`fe314ca`](https://github.com/projectcaluma/alexandria/commit/fe314ca80433de1c866c40fa8673cbb7eee90a80))
=> chore(release): 3.0.0-beta.11

CHANGELOG.md, pyproject.toml
Feature
* Integrate manabi for editing files over WebDAV ([`7e0ec86`](https://github.com/projectcaluma/alexandria/commit/7e0ec86291606945302734579e0868f05cbf73bf))
Is webdav ready for release?
=> chore(release): v3.0.0-beta.14

alexandria/core/serializers.py, alexandria/core/views.py, alexandria/dav.py
- fix: only serve newest File form Document
This is needed for multiple reasons:
1. There is no need to edit old files and the result would probably be
unexpected
2. When creating a new version, Libreoffice doesn't know about this and
it would use the older File as startingpoint. Leading to a new
version on every save.
- fix: only create webDAV links for original Files
- fix: run hooks after file save was successful
- chore: simplify fetching user attributes from request
=> Various fixes for the WebDAV-API

CHANGELOG.md, pyproject.toml
Fix
* **webdav:** Split alexandria provider out of dav.py ([`a0c7d64`](https://github.com/projectcaluma/alexandria/commit/a0c7d64412bc8fada912b94c5206823278a76052))
=> chore(release): 3.0.0-beta.17

alexandria/core/models.py, alexandria/core/serializers.py, alexandria/core/views.py, alexandria/storages/fields.py
We decided to (soon) factor out the file storage code into it's own
proposed module / package, so it can be reused outside of Alexandria.
To ensure we don't forget it next time we work on this code, we're adding
a few TODO lines in context where it may make sense.
See #480 for details
=> chore: add some comments so we don't forget factoring out storage code

CHANGELOG.md, pyproject.toml
Feature
* Add python api for creating files ([#487](https://github.com/projectcaluma/alexandria/issues/487)) ([`a26f058`](https://github.com/projectcaluma/alexandria/commit/a26f0588a6a4365598079283d8dd26d5a580e3e3))
=> chore(release): 3.0.0-beta.18

CHANGELOG.md, pyproject.toml
Feature
* **category:** Define allowed mime types ([`d4fd84e`](https://github.com/projectcaluma/alexandria/commit/d4fd84e6edb0502818f885082217aa48f0e56c5b))
Fix
* **mimetypes:** Cleanup, simplify error handling ([`3bde9c4`](https://github.com/projectcaluma/alexandria/commit/3bde9c490f5ba67d4859767fa37afeabba3f1326))
* **translation:** Use string replacement instead of f string ([`74dd485`](https://github.com/projectcaluma/alexandria/commit/74dd485587e30765bea4a784beead595a33df405))
* **migrations:** Add missing migration for modified by description ([`7f53058`](https://github.com/projectcaluma/alexandria/commit/7f5305820f3e76e1ff6d06bfaa2d7af7d97cd08c))
* **upload:** Use content-type and filename to infer mime types ([`d475321`](https://github.com/projectcaluma/alexandria/commit/d475321d23 …
=> chore(release: v3.1.0

alexandria/conftest.py, alexandria/core/serializers.py, alexandria/core/tests/__snapshots__/test_viewsets.ambr, alexandria/core/tests/test_permissions.py, alexandria/core/tests/test_views.py, alexandria/core/tests/test_viewsets.py
BREAKING CHANGE:
The document post endpoint now requires the file data to be provided as well.
The reason for this change is allowing the frontend to create documents
and files in one request, preventing documents with no associated files.
Which fixes the problem if the file got rejected for any reason, the
application would create an empty document.
=> feat(document)!: create document and file in one request!

README.md, alexandria/core/api.py, alexandria/core/models.py, alexandria/core/serializers.py, alexandria/core/tests/__snapshots__/test_viewsets.ambr, alexandria/core/tests/test_dav.py, alexandria/core/tests/test_views.py, alexandria/core/tests/test_viewsets.py, alexandria/core/tests/test_visibility.py, alexandria/core/validations.py, alexandria/settings/alexandria.py, alexandria/storages/tests/test_dynamic_field.py
This way, the same validations are also triggered when files are uploaded via the python API.
=> fix: move file validation to model

CHANGELOG.md, pyproject.toml
\### Feature
* **document:** Create document and file in one request! ([`444912d`](https://github.com/projectcaluma/alexandria/commit/444912d4cb584c05096ca8a78dd455b8471e9441))
\### Breaking
* The document post endpoint now requires the file data to be provided as well. The reason for this change is allowing the frontend to create documents and files in one request, preventing documents with no associated files. Which fixes the problem if the file got rejected for any reason, the application would create an empty document. ([`444912d`](https://github.com/projectcaluma/alexandria/commit/444912d4cb584c05096ca8a78dd455b8471e9441))
=> chore: release v4.0.0

CHANGELOG.md, pyproject.toml
* **mime:** Allow file extension checking if all fails ([`ddaa134`](https://github.com/projectcaluma/alexandria/commit/ddaa1344b2cde98a0c52f3311772d36da6e28c28))
* Use atomic for document and file creation ([`1a630ad`](https://github.com/projectcaluma/alexandria/commit/1a630adb83a8351d1ed01b3070790e65b00cc43d))
=> chore(release): v4.0.2

README.md, alexandria/core/serializers.py, alexandria/core/views.py, alexandria/oidc_auth/authentication.py, alexandria/settings/alexandria.py
This adds more flexibility when alexandria is used as a package. The consuming app can dictate in more fine grained detail how user and group are set.
=> feat: allow custom implementation of username and group getters

CHANGELOG.md, pyproject.toml
\### Feature
* Allow custom implementation of username and group getters ([`72bf2e4`](https://github.com/projectcaluma/alexandria/commit/72bf2e42862bb72fbd34cda059b8df0aa107ef7a))
=> chore(release): v4.1.0

CHANGELOG.md, pyproject.toml
* **file:** Add search view ([`c9d3766`](https://github.com/projectcaluma/alexandria/commit/c9d37661f7cf4acb0fed55d088f07e7d6cd5d886))
* **file:** Add management command to fill content_vector ([`79b1978`](https://github.com/projectcaluma/alexandria/commit/79b1978ca4b0801cb3eb2edc84340d334d67022f))
* **file:** Add SearchVector field for extracted content ([`b0e5bad`](https://github.com/projectcaluma/alexandria/commit/b0e5baddf41aa03a249bac39c2bc875447cc2c13))
* **file:** Add apache tika for file content extraction ([`0557c59`](https://github.com/projectcaluma/alexandria/commit/0557c5997f6a92055f7b0db56e9a04e93f1f3464))
* **webdav:** Add allowed list of mime types for webdav ([`343a2ee`](https://github.com/projectcaluma/alexandria/commit/343a2eee4b0620c26cec5ced6cd499f5ecb8f4f0))
* …
=> chore(release): v5.0.0

CHANGELOG.md, pyproject.toml
Reverts projectcaluma/alexandria#563
Includes an unreleasable dependency. As the package has not been released to pypi revert the release commit and recreate the release with fix
=> revert: "chore(release): v5.0.0"

alexandria/core/models.py, alexandria/core/tests/test_commands.py, alexandria/core/tests/test_views.py
has some weirdness when using `import tika` instead of the modules directly, sometimes the import works other times it errors with a module not found through `tika.parser`
=> fix(tika): use module path imports

Makefile, README.md, alexandria/core/models.py, alexandria/core/views.py, alexandria/settings/alexandria.py
This prevents files from being not findable when there is no content or a wrong language is detected.
This might make the search a little slower, as were not filtering for the language anymore. But files can always be found, even if the language which tika detected it not in the `LANGUAGE` setting.
=> feat(file): search over all configured stemmings

alexandria/conftest.py, alexandria/core/tests/__snapshots__/test_viewsets.ambr, alexandria/core/tests/test_views.py, alexandria/core/tests/test_viewsets.py, alexandria/core/validations.py, alexandria/core/views.py, alexandria/settings/alexandria.py
This does two things:
- Always deliver files with the mime type that was discovered during
upload
- Enforce the three "signals" for mime types (Cotent-Type header, file
extension, and actual file content) are consistent during file upload
=> fix: mime type handling

.github/workflows/ghcr.yml, .github/workflows/pypi.yml
If a release was created from a draft release,
the created event is not fired but the published is.
=> ci(ghcr): run ghcr on publish an not on created

alexandria/core/models.py, alexandria/core/tests/test_models.py, alexandria/storages/fields.py
Use boto3 built in copy for cloning s3 files instead of fetching and reuploading the same content.
This change should substantially speed up cloning large amount of documents in a real environment with network latency. Locally the difference is not noticeable through the docker network.
=> fix(file): clone files with s3 copy

alexandria/core/tests/test_dav.py, alexandria/dav_provider.py
=> fix(dav): don't create new file if errors were raised

alexandria/core/models.py, alexandria/core/tests/test_models.py, alexandria/storages/fields.py, alexandria/storages/tests/test_dynamic_field.py
fix document clone storage usage
=> fix(storages): use ssec storage at correct times

alexandria/core/tests/test_views.py, alexandria/core/views.py
Should we try to redirect to leave the user on the blank browser default 403 page?
=> fix(file): prevent validation exception for presigned url expiry

alexandria/core/api.py, alexandria/core/management/commands/fix_copied_file_references.py, alexandria/core/tests/test_api.py, alexandria/storages/fields.py, alexandria/storages/tests/test_dynamic_field.py
This is a follow-up on both #757 and #798:
* Pass the bucket *name* to Django storages (not the bucket *object*).
* Copy the `FieldFile` object when copying a document's file, to prevent both files referencing the same object in the storage.
=> Fix file copying

alexandria/dav.py, alexandria/settings/django.py
Django calls a function to close unused/obsolete DB connections before and after each request. In WebDAV, we don't use Django infrastructure to deal with requests, and therefore that cleanup code is not being called.
This introduces a WSGIDav middleware to fix that problem.
However since our unit tests run in transactions, it's a bit uglier (and less tested) than I'd like it to be...
=> fix(webdav): close db connections if unused or obsolete

alexandria/core/tests/test_views.py, alexandria/core/views.py
Files can be renamed, and in the zip download the new name should be used.
Since the document title is free to fill, not regarding any extension, I did add some logic to always remain the original extension in the final result.
=> feat(export): use renamed filenames in export zip

alexandria/core/models.py, alexandria/core/tests/test_models.py, alexandria/core/tests/test_views.py, alexandria/core/views.py
Changed the download filenames in zips reflecting renamed files in https://github.com/projectcaluma/alexandria/pull/869
This MR applies the same in single file downloads
Changed a little bit to reflect the file extension correctly on file versions.
**Example context:**
- Upload a new file `Example.docx`: Download filename is `Example.docx`
- Rename to `Example.test`, Download filename is `Example.test.docx`
- Rename back to `Example.docx`, download filename is `Example.docx`
- Replace the file with a new upload `Example.jpg`, the document title does not change!  (`Example.docx`)
- Download latest file version: download filename is `Example.docx.jpg`
- Download previous file version: download filename is `Example.docx`
- Rename document title to `Example.jpg`
- Download latest file …
=> fix(download): use renamed filename in single and multi download

CHANGELOG.md, pyproject.toml
CHANGELOG:
* **download:** Use renamed filename in single and multi download ([`39d9b93`](https://github.com/nlzet/alexandria/commit/39d9b932e4d79fde875f25bb14dd231d9b5d14a5))
=> chore(release): v8.0.1
