projectcaluma/alexandria

- README.md
- docs/original_alexandria_rfc.md
> docs(rfc): add original rfc

- alexandria/core/filters.py
> feat(document): add filters for category and tags

- alexandria/core/tests/snapshots/snap_test_api.py
- alexandria/core/tests/test_api.py
This helps analyzing possible issues in the serializers and supports
using tests as documentation when you're not sure how to format requests.
CC @fkm-adfinis
> chore(tests): include request payload in generic api test

- alexandria/core/tests/test_slugmodels.py
... also test if workflows work again
> chore(tests): remove misleading docstring

- README.md
- alexandria/core/permissions.py
- alexandria/core/tests/test_permissions.py
- alexandria/core/tests/test_visibility.py
- alexandria/core/visibilities.py
Implement visibility and permission classes that enforce users to be
authenticated.
Extend documentation and while we're at it, document some other important
options as well.
> feat(permissions): authenticated user checks

- alexandria/core/tests/snapshots/snap_test_api.py
- alexandria/core/views.py
- requirements-base.txt
When searching, look in the description field also
> feat: search document description as well

- alexandria/core/factories.py
This helps testing application code. Not actually used "here",
but helpful in customer integrations.
> chore: add meta field to category factory

- alexandria/oidc_auth/authentication.py
- alexandria/oidc_auth/tests/test_authentication.py
- docker-compose.override.yml
- requirements-dev.txt
- setup.cfg
This way, the dev env works out of the box.
> fix: use debug auth backend by default

- .dockerignore
- Dockerfile
- poetry.lock
- pyproject.toml
> fix: use caluma-alexandria as package name

- .github/dependabot.yml
- .github/workflows/ghcr.yml
- .github/workflows/pypi.yml
- CONTRIBUTING.md
- Dockerfile
- Makefile
- README.md
- docker-compose.override.yml
- docker-compose.yml
- poetry.lock
- pyproject.toml
> Docker improvements

- Makefile
- alexandria/core/filters.py
- alexandria/core/tests/test_example_data.py
- initial_data.json
redo dump config, so the new fields are included
> feat(document): add categories filter

- CHANGELOG.md
- pyproject.toml
* **tests:** Fix broken tests ([#415](https://github.com/projectcaluma/alexandria/issues/415)) ([`0bd0cab`](https://github.com/projectcaluma/alexandria/commit/0bd0cab60b1733fd5479affb8dc7ecdec57524ac))
* **file:** Add missing create permission check ([#427](https://github.com/projectcaluma/alexandria/issues/427)) ([`34a57c1`](https://github.com/projectcaluma/alexandria/commit/34a57c1001be5d574676d77d5dab22ab7338db99))
* Remove modified at update for file creation ([#425](https://github.com/projectcaluma/alexandria/issues/425)) ([`86cfbf2`](https://github.com/projectcaluma/alexandria/commit/86cfbf2245f54e2126cc51329110a744a2752a4d))
> chore(release): v3.0.0-beta.5

- alexandria/core/management/commands/encrypt_files.py
> fix: remove dry from encryption command

- CHANGELOG.md
- pyproject.toml
* Add optional dms integration ([`38ecbec`](https://github.com/projectcaluma/alexandria/commit/38ecbec4e2c5cb088be4a74abd81b3cadbeb1ea5))
* **dms:** Return json document after conversion ([`357bae9`](https://github.com/projectcaluma/alexandria/commit/357bae96e433a128622edcc0bc6754d5520d3c81))
* **dms:** Improve dms integreation ([`4bbf1c3`](https://github.com/projectcaluma/alexandria/commit/4bbf1c3aaec78a48138400cf3cf252defd6e61ec))
> chore(release): v3.0.0-beta.12

- CHANGELOG.md
- pyproject.toml
* **convert:** Copy over metainfo ([#468](https://github.com/projectcaluma/alexandria/issues/468)) ([`4d0b7c0`](https://github.com/projectcaluma/alexandria/commit/4d0b7c0f995e2065443fdd6fc2a9328cd97fd20b))
> chore(release): v3.0.0-beta.14

- alexandria/core/serializers.py
use the provided helper function to extract the attributes, which checks for anonymous aswell
> fix(webdav): fix anonymous user attributes

- README.md
- alexandria/core/serializers.py
- alexandria/core/tests/__snapshots__/test_viewsets.ambr
- alexandria/core/tests/test_dav.py
- alexandria/core/tests/test_permissions.py
- alexandria/core/tests/test_viewsets.py
- alexandria/core/urls.py
- alexandria/core/views.py
- alexandria/oidc_auth/authentication.py
- alexandria/settings/alexandria.py
- poetry.lock
- pyproject.toml
REFACTOR: remove dav url from file serializer
> feat(dav)!: dav url to sperate view

- alexandria/core/management/commands/generate_content_vectors.py
- alexandria/core/tests/test_commands.py
prevents cancellation of command if one of the files is not found
> fix(file): improve content vector generation command

- CHANGELOG.md
- pyproject.toml
* Improve content vector generation command (145ae23aee4241922af21d88d88050423c3d894b)
* Use module path imports (2df7b7ad814905de87c9bb3a8be9c5ec8f0e707b)
> chore(release): v5.0.1

- alexandria/core/management/commands/generate_content_vectors.py
- alexandria/core/models.py
- alexandria/core/tests/test_commands.py
Improves the generation management command to be more resilient and less error prone on long runs.
Adds handling when tika does not detect any content.
> fix(file): improve content vector generation

- CHANGELOG.md
- pyproject.toml
\### Fix
* fix(file): improve content vector generation ([`b6841da`](https://github.com/projectcaluma/alexandria/commit/b6841da326198065d5d838febf360eaf28aa0389))
* refactor(file): move check for optional feature methods ([`a8420c5`](https://github.com/projectcaluma/alexandria/commit/a8420c5597579809d759a0d7d0daca8768f04379))
> chore(release): v5.0.2

- CHANGELOG.md
- pyproject.toml
* Search over all configured stemmings (1d9cca20db4d5054fa55cb8db490db3eebbe53b5)
* Allow opening webdav links with custom URI schemes (9f4516631dfb25aa5bcbf3b3500bcb5d0ab131be)
> chore(release): v5.1.0

- alexandria/core/tests/test_views.py
- alexandria/core/views.py
This fixes a regression introduced in 39436b7739d8a06c9da2a51f7a7b5bed82a84d4c
> fix(convert): change file extension in document title on conversion

- CHANGELOG.md
- pyproject.toml
Feature
* Add celery to allow for background tasks (d6f995c5137b01fc2366bbf1011ea56a0a6c17a7)
> chore(release): v6.2.0

- alexandria/core/filters.py
- alexandria/core/views.py
Moving the search code to a filterset allows us to use the regular filters that we have on files on the search endpoint as well. Also, it's cleaner to have QS filtering in the filterset instead of the viewset anyway.
> refactor(search): move the fulltext search code to a proper filterset

- alexandria/core/filters.py
- alexandria/core/views.py
Moving the search code to a filterset allows us to use the regular filters that we have on files on the search endpoint as well. Also, it's cleaner to have QS filtering in the filterset instead of the viewset anyway.
Note: This is a Re-commit of #641 as a feature to fix semantic release's versioning
> feat(search): move the fulltext search code to a proper filterset

- CHANGELOG.md
- pyproject.toml
Feature
* Move the fulltext search code to a proper filterset (088a897820f88e3078bd20488ca0437e575a8372)
> chore(release): v6.3.0

- CHANGELOG.md
- pyproject.toml
Feature
* Remove category filter (b9126f06f1317b25bd239594dd42956bc158cc31)
* Add document title and description to search (71fd43f428cbf40e1e8b303f31b1a4cf4dbb607a)
* Search utility (e96aff8f6a6819eb4981b3bd75b51f9aca03f281)
* Add "only_newest" filter for files (2b42cb9f17a38c6b3bb73b406fc1fe1969f64528)
* Implement improved fulltext search (99a007827c87b158b4e0560acdde03cffab8dccc)
* Move thumbnail generation to celery (6d30dcd0533be084b8596cc1536ca69894fdc174)
Fix
* Clone files with s3 copy (f191fae359110cb32e55e5315c45139d627d46a6)
* Update DGAP (c2c357b74f5409b92700f1724afae85be3b4b2e2)
* Revalidate mimetypes after moving document to different category (46066ac030808fde94bfc263f8b303e21bea0482)
* Remove version from errors (e39470f77183be42e3761abe0abf0fe15c1e174f)
* Stricter mime …
> chore(release): v7.0.0

- alexandria/core/api.py
- alexandria/core/serializers.py
- alexandria/core/tests/test_api.py
- alexandria/core/tests/test_views.py
- alexandria/core/utils.py
- alexandria/core/views.py
- alexandria/locale/de/LC_MESSAGES/django.po
- alexandria/locale/en/LC_MESSAGES/django.po
Adding a new API endpoint to copy a document with underlying files
> feat(copy): add api endpoint to copy a document

- CHANGELOG.md
- pyproject.toml
* **storages:** Move copy to storage field ([`1d55d90`](https://github.com/projectcaluma/alexandria/commit/1d55d9043a362207d8559c6ec6ea21e5aba7cd78))
> chore: release v7.2.0
